person:
  name: qinjiang
  age: 3
  happy: false
  birth: 2019/11/02
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - music
  dog:
    name: wangcai
    age: 3


---
server:
  port: 8082
spring:
  config:
    activate:
      on-profile:
